character_text_splitter:
  chunk_size: 1000
  chunk_overlap: 200
  separator: "\n\n"
  keep_separator: False

recursive_text_splitter:
  chunk_size: 500
  chunk_overlap: 100
  separators: ["\n\n", "\n", " ", ""]

recursive_character_text_splitter:
  chunk_size: 200
  chunk_overlap: 100
  separators: ["\n\n", "\n", " ", ""]
  length_function: "len"
  is_separator_regex: False

markdown_header_metadata_splitter:
  headers_to_split_on: [
    ["#", "Header 1"],
    ["##", "Header 2"],
    ["###", "Header 3"]
  ]
  return_each_line: False
  strip_headers: True

semantic_splitter:
  embeddings_model: "text-embedding-ada-002"
  buffer_size: 1
  breakpoint_threshold_type: "percentile"
  breakpoint_threshold_amount: 95