character_text_splitter:
  chunk_size: 5000
  chunk_overlap: 200
  separator: "\n\n"
  keep_separator: False

recursive_character_text_splitter:
  chunk_size: 1000
  chunk_overlap: 100
  separators: ["\n\n", "\n", " ", ""]
  length_function: "len"
  is_separator_regex: False

markdown_header_metadata_splitter:
  headers_to_split_on: [
    ["#", "Header 1"],
    ["##", "Header 2"],
    ["###", "Header 3"]
  ]
  return_each_line: False
  strip_headers: True

semantic_splitter:
  recursive_params:
    chunk_size: 100000
    chunk_overlap: 1000
    separators: ["\n\n", "\n", " ", ""]
    keep_separator: False
  semantic_params:
    embeddings: "text-embedding-3-small"
    buffer_size: 1
    breakpoint_threshold_type: "percentile"
    breakpoint_threshold_amount: 95